services:
    MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\Gateway\DoctrineDatabase:
        arguments:
            $connection: '@ezpublish.persistence.connection'
            $contentGateway: '@ezpublish.persistence.legacy.content.gateway.inner'
            $locationGateway: '@ezpublish.persistence.legacy.location.gateway'
            $fieldHandler: '@ezpublish.persistence.legacy.field_handler'

    MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\Gateway\PageFieldTypeDoctrineDatabase:
        arguments:
            $connection: '@ezpublish.persistence.connection'
            $pageFieldTypeGateway: '@?EzSystems\EzPlatformPageFieldType\FieldType\Page\Storage\DoctrineGateway'

    MateuszBieniek\EzPlatformDatabaseHealthCheckerBundle\Command\DatabaseHealthCheckCommand:
        arguments:
            $contentGateway: '@MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\Gateway\DoctrineDatabase'
            $contentService: '@ezpublish.api.service.content'
            $locationService: '@ezpublish.api.service.location'
            $siteAccess: '@ezpublish.siteaccess'
            $permissionResolver: '@eZ\Publish\API\Repository\PermissionResolver'
            $handler: '@ezpublish.api.storage_engine'
            $repository: '@ezpublish.api.repository'
        tags:
            - { name: 'console.command', command: 'ezplatform:database-health-check' }

    MateuszBieniek\EzPlatformDatabaseHealthCheckerBundle\Command\PageFieldTypeCleanupCommand:
        arguments:
            $gateway: '@MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\Gateway\PageFieldTypeDoctrineDatabase'
        tags:
            - { name: 'console.command', command: 'ezplatform:page-fieldtype-cleanup' }

    cache.null:
        class: Symfony\Component\Cache\Adapter\NullAdapter
        arguments: [~]
        tags:
            - name: cache.pool
              clearer: cache.app_clearer
              namespace: '%cache_namespace%'
