services:
    MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\DoctrineDatabase:
        arguments:
            $connection: '@ezpublish.persistence.connection'

    MateuszBieniek\EzPlatformDatabaseHealthCheckerBundle\Command\DatabaseHealthCheckCommand:
        arguments:
            $contentGateway: '@MateuszBieniek\EzPlatformDatabaseHealthChecker\Persistence\Legacy\Content\DoctrineDatabase'
        tags:
            - { name: 'console.command', command: 'ezplatform:database-health-check' }
